name: Dependabot PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  quality-check:
    uses: ./.github/workflows/quality-check.yml
    with:
      node-version: '20'
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
