name: Dependabot PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  dependabot_checks:
    runs-on: ubuntu-latest
    name: Dependabot Checks
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Run Common Quality Checks
        uses: ./.github/actions/checks
        with:
          node-version: '20'
