name: Common Quality Checks

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  quality_checks:
    runs-on: ubuntu-latest
    name: Run Quality Checks
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Lint Code
        run: npm run lint
      - name: Check for Vulnerabilities
        run: npm audit
